// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EK19yUgJ31v3JuT2AVRRmvSCuWZACq4',
    appId: '1:332281449681:web:c974508a8454b1cc1689f0',
    messagingSenderId: '332281449681',
    projectId: 'qr-code-form-b7550',
    authDomain: 'qr-code-form-b7550.firebaseapp.com',
    databaseURL: 'https://qr-code-form-b7550-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qr-code-form-b7550.appspot.com',
    measurementId: 'G-XYWHNVV4W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC456YFtq10dLzt4yVgjAbuy7HcdPhn7kE',
    appId: '1:332281449681:android:101e02359ae526ab1689f0',
    messagingSenderId: '332281449681',
    projectId: 'qr-code-form-b7550',
    databaseURL: 'https://qr-code-form-b7550-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qr-code-form-b7550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOVocs9XeLJA_fwp_y2xa6m4fUS1icmcg',
    appId: '1:332281449681:ios:e3cdd28643a69c561689f0',
    messagingSenderId: '332281449681',
    projectId: 'qr-code-form-b7550',
    databaseURL: 'https://qr-code-form-b7550-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qr-code-form-b7550.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOVocs9XeLJA_fwp_y2xa6m4fUS1icmcg',
    appId: '1:332281449681:ios:e3cdd28643a69c561689f0',
    messagingSenderId: '332281449681',
    projectId: 'qr-code-form-b7550',
    databaseURL: 'https://qr-code-form-b7550-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qr-code-form-b7550.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2EK19yUgJ31v3JuT2AVRRmvSCuWZACq4',
    appId: '1:332281449681:web:492d21b34fe777ba1689f0',
    messagingSenderId: '332281449681',
    projectId: 'qr-code-form-b7550',
    authDomain: 'qr-code-form-b7550.firebaseapp.com',
    databaseURL: 'https://qr-code-form-b7550-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qr-code-form-b7550.appspot.com',
    measurementId: 'G-6YWDF6JGPJ',
  );
}
